try to fix azp initial tests silent fails

diff --git a/azure-pipelines.yml b/azure-pipelines.yml
--- a/azure-pipelines.yml
+++ b/azure-pipelines.yml
@@ -38,8 +38,22 @@ jobs:
       displayName: "Python Setup"
       
     - bash: |
-        make test
-        make clean 
+        echo '##[group]Installing Dependencies'
+        pip install -e .[test] -v
+        echo '##[endgroup]''
+
+        echo '##[group]Build Inplace'
+        make
+        echo '##[endgroup]''
+
+        echo '##[group]Running Test'
+        pytest || exit 1
+        echo '##[endgroup]''
+
+        echo '##[group]Cleanup'
+        make clean
+        pip uninstall dfit
+        echo '##[endgroup]''
       displayName: "Initial Build Tests"
       
     - bash: |
